-- CREATE DATABASE customers;

CREATE USER admin WITH PASSWORD 'test25**';

CREATE DATABASE customers_db WITH
    OWNER admin
    ENCODING 'UTF8'
    LC_COLLATE 'en_US.UTF-8'
    LC_CTYPE 'en_US.UTF-8'
    TEMPLATE template0;

GRANT ALL PRIVILEGES ON DATABASE customers_db TO admin;

-- CREATE SCHEMA
CREATE SCHEMA cs AUTHORIZATION admin;
CREATE SCHEMA pay AUTHORIZATION admin;
CREATE SCHEMA ctg AUTHORIZATION admin;
CREATE SCHEMA ship AUTHORIZATION admin;